"""jobs.parsed_document_uri

Revision ID: 8d5dbf03a4ab
Revises: 1b5898ed1b2a
Create Date: 2026-05-03 17:52:39.782737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d5dbf03a4ab'
down_revision: Union[str, None] = '1b5898ed1b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('parsed_document_uri', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'parsed_document_uri')
    # ### end Alembic commands ###
